name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v2

      - name: Setup Node.js ğŸ—
        uses: actions/setup-node@v2.5.3
        with:
          node-version: 16

      - name: Get yarn cache directory path ğŸ› 
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV

      - name: Cache node_modules ğŸ“¦
        uses: actions/cache@v2
        with:
          path: ${{ env.YARN_CACHE_DIR }}
          key: ubuntu-latest-yarn-${{ hashFiles('new-web/yarn.lock') }}

      - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
        working-directory: new-web
        run: yarn install

      - name: Run linter ğŸ‘€
        working-directory: new-web
        run: yarn lint

      - name: Run tests ğŸ§ª
        working-directory: new-web
        run: yarn test
